name: .NET Core
on:
  workflow_dispatch:
  push:
    paths:
      - 'ManifestUpdater/Resources/internal_manifest.json'
  # Every 30 minutes. This should be safe, GitHub limit is 1000 / hour and Nexus is 500 / hour.
  schedule:
  - cron: "0/30 * * * *"
      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEXUS_APITOKEN: ${{ secrets.NEXUS_APITOKEN }}
jobs:

  build:
    runs-on: windows-latest
    steps:

    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    - name: Run Updater
      run: dotnet run --project ./ManifestUpdater 
